# Generated by Django 6.1 on 2026-08-29 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coworkings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Забронировавший пользователь'),
        ),
        migrations.AddConstraint(
            model_name='coworking',
            constraint=models.UniqueConstraint(fields=('address', 'city'), name='unique_city_address'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('coworking', 'name', 'type'), name='unique_place_per_coworking'),
        ),
    ]
